language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - composer self-update
  - composer install

before_script:
  - php vendor/bin/codecept build

script:
  - php vendor/bin/codecept run --coverage --coverage-xml

after_success:
  - php vendor/bin/php-coveralls
