language: php
php:
  - '7.4'
  - '8.0'

install:
  - composer self-update
  - composer install

script:
  - XDEBUG_MODE=coverage php vendor/bin/phpunit

after_success:
  - php vendor/bin/php-coveralls
