language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - composer self-update
  - composer install

before_script:
  - php vendor/bin/codecept build

script:
  - php vendor/bin/codecept run --coverage
